name: 'Build Kas'
description: 'Build a KAS target'
inputs:
  target:  # id of input
    description: 'target'
    required: false
  command:  # command
    description: 'command'
    required: false
  config-dir:  # command
    description: 'bitbake arguments'
    required: false
  bitbake-args:  # command
    description: 'bitbake arguments'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    KAS_BUILD_ACTION_CONFIG_DIR: ${{ inputs.config-dir }}
    KAS_BUILD_ACTION_TARGET: ${{ inputs.target }}
    KAS_BUILD_ACTION_COMMAND: ${{ inputs.command }}
    KAS_BUILD_ACTION_BBARGS: ${{ inputs.bitbake-args }}

