header:
    version: 16
repos:
    meta-freescale:
        commit: 0f8091c63dd8805610c09b08409bc58492a3b16f
        url: https://github.com/Freescale/meta-freescale.git
    meta-freescale-3rdparty:
        commit: 8b61684f0b1ba8bacdf3a69d993445e9791d4932
        url: https://github.com/Freescale/meta-freescale-3rdparty.git
    meta-freescale-distro:
        commit: b9d6a5d9931922558046d230c1f5f4ef6ee72345
        url: https://github.com/Freescale/meta-freescale-distro.git
    meta-openembedded:
        layers:
            meta-multimedia:
            meta-filesystems:
            meta-networking:
            meta-oe:
            meta-python:
        url: https://github.com/openembedded/meta-openembedded.git
        commit: 2338409efc51cf2022ff5610a9fb689251706e2b
    meta-imx:
        url: https://github.com/nxp-imx/meta-imx.git
        branch: scarthgap-6.6.23-2.0.0
        layers:
            meta-imx-bsp:
            meta-imx-ml:
            meta-imx-sdk:
        commit: ae04eecd48e557437ec90366795b8cf202d0ce14
    meta-arm:
        commit: 38bce82e42ea093333a53c4a10e51d1b26cbc989
        layers:
            meta-arm:
            meta-arm-toolchain:
        url: git://git.yoctoproject.org/meta-arm
    meta-pantavisor:
    poky:
        url: https://github.com/yoctoproject/poky.git
        layers:
            meta:
            meta-poky:
        patches:
            fit-image-multiconfig:
                path: patches/poky/0001-fit-image-multiconfig.scarthgap.patch
                repo: meta-pantavisor
        commit: 0b37512fb4b231cc106768e2a7328431009b3b70
    meta-virtualization:
        commit: 54b806b1985f3989722ee308e1073530fe3328c1
        url: git://git.yoctoproject.org/meta-virtualization
local_conf_header:
    platform-freescale: |
        ACCEPT_FSL_EULA = "1"
    platform-nxp: |
        PV_UBOOT_AUTOFDT = "1"
        VIRTUAL-RUNTIME_initscripts = "initscripts-pv"
        EXTRA_IMAGE_FEATURES = "debug-tweaks"
        PANTAVISOR_MACHINE_FIRMWARE = ""
        PANTAVISOR_MACHINE_KERNEL_MODULES = ""
        PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
    panta-base: |
        TMPDIR = "${TOPDIR}/tmp-${DISTRO_CODENAME}"
    panta-busybox: |
        PREFERRED_VERSION_busybox = "1.36~pv.%"
    panta-mbedtls: |
        PREFERRED_VERSION_mbedtls = "2.28.%"
    pantavisor-system: |
        DISTRO_FEATURES:append = " pantavisor-system "
        PANTAVISOR_FEATURES:append = " dm-crypt"
        PANTAVISOR_FEATURES:append = " dm-verity"
        INITRAMFS_IMAGE = "pantavisor-initramfs"
    pantavisor-remix: |
        IMAGE_CLASSES:append = " image-pvrexport"
    __menu_config_locals: ''
    __menu_config_vars: |-
        PVROOT_IMAGE = "yes"
        PVROOT_IMAGE_BSP = "core-image-base"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    __voldirs: |-
        SSTATE_DIR="/shared/sstate"
        DL_DIR="/shared/dldir"
bblayers_conf_header:
    platform-nxp: |
        BBMASK += "meta-imx/meta-bsp/recipes-bsp/firmware-imx/firmware-imx.*"
        BBMASK += "meta-imx/meta-imx-bsp/recipes-bsp/firmware-imx/firmware-imx.*"
machine: imx8qxpc0mek
target:
- pantavisor-remix
build_system: oe
env:
    PVROOT_IMAGE_BSP:
    PV_BOOT_OEMARGS:
defaults:
    repos:
        branch: scarthgap
_source_dir: .
