header:
    version: 16
repos:
    meta-raspberrypi:
        commit: 1918a27419dcd5e79954c0dc0edddcde91057a7e
        patches:
            uboot-env:
                path: patches/meta-raspberrypi/0001-fix-conflicting-boot.scr-from-of-u-boot-and-u-boot-d.patch
                repo: meta-pantavisor
        path: meta-raspberrypi
        url: https://github.com/agherzan/meta-raspberrypi
    meta-qt5:
        commit: eb828418264a49b8d00035cb3d7b12fcea3be801
        path: meta-qt5
        url: https://github.com/meta-qt5/meta-qt5/
    meta-pantavisor:
    poky:
        url: https://github.com/yoctoproject/poky.git
        layers:
            meta:
            meta-poky:
        patches:
            fit-image-multiconfig:
                path: patches/poky/0001-fit-image-multiconfig.scarthgap.patch
                repo: meta-pantavisor
        commit: 0b37512fb4b231cc106768e2a7328431009b3b70
    meta-virtualization:
        commit: 54b806b1985f3989722ee308e1073530fe3328c1
        url: git://git.yoctoproject.org/meta-virtualization
    meta-openembedded:
        commit: 2338409efc51cf2022ff5610a9fb689251706e2b
        layers:
            meta-filesystems:
            meta-networking:
            meta-oe:
            meta-python:
        url: https://github.com/openembedded/meta-openembedded.git
local_conf_header:
    platform-raspberrypi: |
        LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
        RPI_USE_U_BOOT = "1"
        ENABLE_UART = "1"
    panta-base: |
        TMPDIR = "${TOPDIR}/tmp-${DISTRO_CODENAME}"
    panta-busybox: |
        PREFERRED_VERSION_busybox = "1.36~pv.%"
    panta-mbedtls: |
        PREFERRED_VERSION_mbedtls = "2.28.%"
    pantavisor-system: |
        DISTRO_FEATURES:append = " pantavisor-system "
        PANTAVISOR_FEATURES:append = " dm-crypt"
        PANTAVISOR_FEATURES:append = " dm-verity"
        INITRAMFS_IMAGE = "pantavisor-initramfs"
    pantavisor-remix: |
        IMAGE_CLASSES:append = " image-pvrexport"
    __menu_config_locals: ''
    __menu_config_vars: |-
        PVROOT_IMAGE = "yes"
        PVROOT_IMAGE_BSP = "core-image-base"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    __voldirs: |-
        SSTATE_DIR="/shared/sstate"
        DL_DIR="/shared/dldir"
machine: raspberrypi-armv8
target:
- pantavisor-remix
build_system: oe
env:
    PVROOT_IMAGE_BSP:
    PV_BOOT_OEMARGS:
defaults:
    repos:
        branch: scarthgap
_source_dir: .
